//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int Id { get; set; }
        public int amount { get; set; }
        public double interest { get; set; }
        public double payment_per_month { get; set; }
        public int emp_id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
