//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterial
    {
        public RawMaterial()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
